
# The name of your website.
name: Statify
displayed_name: Statify

description:

  # Description of your site. This will show up in google.
  meta: Développeur Web Freelance | Fullstack Ruby on Rails | Lyon

  # Description of your site. This will show up on the front page.
  subtitle: CTO chez <a href="https://lesdechaines.fr" target="_blank">Les Déchaînés</a> | Remote Worker | Product builder

author:
  name: Grégoire # Change this!

  # Necessary for contact page
  email: gregoire.castellazzi@gmail.com # Change this!

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

# language attribute in <html> element.
lang: en

sass:
  style: compressed

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: false

footer-text: This is the footer.<br><a href="http://steinvc.github.io/holo-alfa/">Holo Alfa</a> Jekyll theme crafted by <a href="http://steinvc.github.io/holo-alfa/">Stijn</a>.

# Preferably 64px in height. Leave empty = disable.
logo-image: /img/gregoire_photo.jpg

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%d/%m/%Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname: gregocastel


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram:
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github:
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Lire # Text after each post summary on the homepage.
var_newer: Plus récents
var_older: Plus anciens
var_next_post: Post suivant
var_previous_post: Post précédent
var_less_than_a_minute_read: Moins d'une minute de lecture
var_min_read: minutes de lecture # Text after reading time. Example: 5 min read.
var_post_by: Publié par
var_guest_post_by: (Invité) Publié par
var_your_email: Votre e-mail
var_your_message: Votre message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: []
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
